project:
  type: book
  output-dir: _book

book:
  title: "P // WLM 2023"
  subtitle: "Материалы практики"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: last-modified
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - pr1.qmd
    - pr2.qmd
    - pr3.qmd
    - pr4.qmd
    - pr5.qmd
    # - pr6.qmd
    - pr7.qmd
    - pr8.qmd
    - pr9.qmd
    # - pr10.qmd
    - pr11.qmd
    # - pr12.qmd
    - pr13.qmd
    - pr14.qmd
    # - pr15.qmd
    # - pr16.qmd
    # - pr17.qmd
    - references.qmd
  favicon: pics/favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    left: 
      - text: "Хаб"
        href: ../hub/index.html
      - text: "Лекции"
        href: ../lectures/index.html
      - text: "Практики"
        href: ../practice/index.html
      - text: "Домашки"
        href: ../homeworks/index.html
      - text: "Проекты"
        href: ../projects/index.html
    collapse: true
    background: gray-700


bibliography: references.bib

comments:
  hypothesis: true
  
format:
  html:
    callout-appearance: simple
    cover-image: pics/pr-cover.png
    theme: 
      light: [css/lightstyle.scss, css/style.scss]
      dark: [css/darkstyle.scss, css/style.scss]
  pdf:
    documentclass: scrreprt

editor: source

