# L2 // Предобработка данных. Дата и время Визуализация данных

## Работа с данными

## Организация рабочего пространства

## Projects

## Форматы данных

## Кодировка

## Локаль

## Первичное исследование данных



## Предобработка данных

## Концепция Tidy Data

## Семейство пакетов `tidyverse`

## Импорт данных

## Переименование переменных

## Фильтрация данных. Строки

## Фильтрация данных. Столбцы

## Сортировка данных

## Создание и изменение переменных

## Группировка и аггрегация данных

## Объединение датасетов. Строки и столбцы

## Объединение датасетов. Ключ

## Широкий и длинный форматы данных



## Строки

## Операции над строками

## Регулярные выражения

## Дата и время

## Форматы даты и времени

## Операции над датами



## Визуализация данных

## Зачем нужна визуализация?

## Виды графиков. Bar plot
## Виды графиков. Histogram
## Виды графиков. Density plot
## Виды графиков. Dot plot
## Виды графиков. Boxplot
## Виды графиков. Violin plot
## Виды графиков. Error bar
## Виды графиков. Line plot
## Виды графиков. Scatter plot
## Виды графиков. Corrplot

## Good & Bad practices в визуализации
## Основные ошибки в визуализации
## Философия A Layered Grammar of Graphics
## `ggplot2`


