project:
  type: book
  output-dir: _book

book:
  title: "J & F // WLM 2023"
  subtitle: "Проекты"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: last-modified
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - j.qmd
    - f.qmd
    - references.qmd
  favicon: pics/favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    left: 
      - text: "Хаб"
        href: ../hub/index.html
      - text: "Лекции"
        href: ../lectures/index.html
      - text: "Практики"
        href: ../practice/index.html
      - text: "Домашки"
        href: ../homeworks/index.html
      - text: "Проекты"
        href: ../projects/index.html
    collapse: true
    background: gray-700


bibliography: references.bib

comments:
  hypothesis: true

format:
  html:
    cover-image: pics/proj-cover.png
    theme: 
      light: [css/lightstyle.scss, css/style.scss]
      dark: [css/darkstyle.scss, css/style.scss]
  pdf:
    documentclass: scrreprt

editor: source

