project:
  type: website
  output-dir: _book

website:
  title: "WLM 2023"
  favicon: pics/favicon.png
  # sidebar:
  #   style: "docked"
  #   search: false
  #   contents:
  #   - index.qmd
  #   - what-is-it.qmd
  #   - how-is-it-made.qmd
  #   - how-to-use.qmd
  #   - how-to-support.qmd
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    left: 
      - text: "Хаб"
        href: ../hub/index.html
      - text: "Лекции"
        href: ../lectures/index.html
      - text: "Практики"
        href: ../practice/index.html
      - text: "Домашки"
        href: ../homeworks/index.html
      - text: "Проекты"
        href: ../projects/index.html
    collapse: true
    background: gray-700
  page-footer: 
    left: "© 2023--2024, Anton Angelgardt" 
    right: 
      - icon: github
        href: https://github.com/angelgardt

format:
  html:
    grid: 
      body-width: 900px
    theme: 
      light: [lightstyle.scss]
      dark: [darkstyle.scss]
    css: styles.css
    toc: true

highlight-style: github
