---
title: "WLM 2023"
subtitle: "Анализ данных и машинное обучение для исследователей"
---

## Лекции // Квизы

* [Плейлист с лекциями](https://www.youtube.com/playlist?list=PL3GWEmQN96bvRRnuxcp_jLE3_3GcQ7a2-)
* [Книжка с конспектами](../lectures/)

| Лекции    | Записи      | Слайды      | Конспекты     | Квизы |
|-----------|-------------|-------------|---------------|-------|
| L1 // Основы R. Типы и структуры данных. Функции и управляющие конструкции  | [L1.1 // Основы R. Типы и структуры данных.](https://youtu.be/lHsG-Z-kFHE?si=8WGnPTPuBLwjvk0h) <br> [L1.2 //  Основы R. Функции и управляющие конструкции](https://youtu.be/vkE0C7bozh0?si=-a7BIY7AZ3p6gvCv)  | [L1 // Слайды](../slides/s1.html)  | [L1 // Конспект](../lectures/l1.html)  | [Q1](https://forms.gle/LHpf21zonJHXY7sQ6)    |
| L2 // Предобработка данных. Строки. Дата и время. Визуализация данных  | [L2.1 // Работа с данными](https://youtu.be/unk_whpLZ0c?si=jqs1_AUUsaNJWB-1) <br> [L2.2 // Предобработка данных](https://youtu.be/ZX5Nyw_8ph0?si=7aiUAff8jnaBGDC7) <br> [L2.3 // Визуализация данных](https://youtu.be/N-J1mX4K-kA?si=VR6Gs9tcd-p1zn-5) | [L2 // Слайды](../slides/s2.html)  | [L2 // Конспект](../lectures/l2.html)  | [Q2](https://forms.gle/dN3i9zRveUCaj32Q7)    |
| L3 // Математика для анализа данных  | [L3.1 // Дискретная математика](https://youtu.be/XXJZv1i0fsw?si=Lxbpu343ak_7tvtf) <br> [L3.2 // Математический анализ](https://youtu.be/UN-TCFwsDxc?si=SZOleyAfEO6uV2ug) <br> [L3.3 // Линейная алгебра](https://youtu.be/Dg6TkDvQa3E?si=fHGxZ1TtANhnDs_Y) | [L3 // Слайды](../slides/s3.html)  | [L3 // Конспект](../lectures/l3.html)  | [Q3](https://forms.gle/FGVyMEKHGPoCBLS28)    |
| L4 // Теория измерений  | [L4.1 // Измерения и шкалы](https://youtu.be/-o2PrjQlP1M?si=R_aPSxQj8mXUmcHs) <br> [L4.2 // Психометрические измерения](https://youtu.be/TiBaTCm1as8?si=sX0qEzfiXLW1jQIl)  | [L4 // Слайды](../slides/s4.html)  | [L4 // Конспект](../lectures/l4.html)  | [Q4](https://forms.gle/116ozrSuxaB9n2Z28)    |
| L5 // Введение в статистику. Случайный эксперимент и случайные величины  | [L5.1 // Введение в математическую статистику](https://youtu.be/3ymMNaYpAPg?si=x0BfjmLlA4j1gP0E) <br> [L5.2 // Случайный эксперимент](https://youtu.be/A5sxyateCJY?si=jh3wXyjs6ldbhGES) <br> [L5.3 // Случайные величины](https://youtu.be/qCOFwD21QX8?si=5siO5Vbm--iyEypt)  | [L5 // Слайды](../slides/s5.html)  | [L5 // Конспект](../lectures/l5.html)  | [Q5](https://forms.gle/bMvV6TMpToC5c3DAA)    |
| L6 // Оценивание статистических параметров. Тестирование статистических гипотез  | [L6.1 // Оценивание статистических параметров](https://youtu.be/x2A_dIv8flo?si=IQ0AN2ZlMaGn6o12) <br> [L6.2 // Тестирование статистических гипотез](https://youtu.be/CIZNstoanNU?si=JIm9GDtaqB5IWycP)  | [L6 // Слайды](../slides/s6.html)  | [L6 // Конспект](../lectures/l6.html)  | [Q6](https://forms.gle/ET6KZ1Vcb5yM7mxcA)    |
| L7 // Описательные статистики. Корреляционный анализ  | [L7.1 // Описательные статистики](https://youtu.be/hHHBDs0PSA4?si=xi53_Hh-KRHv-p0D) <br>  [L7.2 // Корреляционный анализ](https://youtu.be/6qx8ZfOmg4M?si=xZou08VI4ixeTfoO) | [L7 // Слайды](../slides/s7.html)  | [L7 // Конспект](../lectures/l7.html)  | [Q7](https://forms.gle/krkMM2KSMjF6A8gx8)    |
| L8 // Общие линейные модели. Простая и множественная линейная регрессия  | [L8.1 // Простая линейная регрессия](https://youtu.be/uhiso3MkoDs?si=4MyYvwjV4oy-4FpQ) <br> [L8.2 // Множественная линейная регрессия](https://youtu.be/7OUJhe19KWA?si=FVlNZcGk52PFr_v0) | [L8 // Слайды](../slides/s8.html)  | [L8 // Конспект](../lectures/l8.html)  | [Q8](https://forms.gle/JGpj7i5Dt7mhKxWf9)    |
| L9 // Дисперсионный анализ. Ковариационный анализ  | [L9.1 // Однофакторный дисперсионный анализ](https://youtu.be/iE_-Ub4LVpI?si=JRxEW_LG-7gUiHLJ) <br> [L9.2 // Многофакторный дисперсионный анализ](https://youtu.be/PsBJLn7sc48?si=Y_x2MHsL0Qrj2yTc) <br> [L9.3 // Ковариационный анализ](https://youtu.be/04y69tO72ZY?si=B70hz20q9EQE8Mrh) | [L9 // Слайды](../slides/s9.html)  | [L9 // Конспект](../lectures/l9.html)  | [Q9](https://forms.gle/YrFGUUa9AJ6SyeGE6)    |
| L10 // Обобщенные линейные модели. Логистическая регрессия. Пуассоновская регрессия | [L10.1 // Логистическая регрессия](https://youtu.be/S9FW_aGXCnQ?si=wV9ybrRTYDGXLqd0) <br> [L10.2 // Пуассоновская регрессия](https://youtu.be/OSMIcJHQQa4?si=q9Yc4MWn5SVZZoSV) | [L10 // Слайды](../slides/s10.html) | [L10 // Конспект](../lectures/l10.html) | [Q10](https://forms.gle/M6pvyLguN2RUpyES8)   |
| L11 // Обобщенные аддитивные модели. Регуляризация регрессии | [L11.1 // Обобщенные аддитивные модели](https://youtu.be/EZu99HUQ714?si=DqQwKfyLPSdjl982) <br> [L11.2 // Регуляризация регрессии](https://youtu.be/XRyU8_nuZkk?si=dv0g-kKdJytzTAeU) | [L11 // Слайды](../slides/s11.html) | [L11 // Конспект](../lectures/l11.html) | [Q11](https://forms.gle/cwBq9AdWEFCax3Pi9)   |
| L12 // Линейные модели со смешанными эффектами | [L12 // Смешанные линейные модели](https://youtu.be/W3ivdjpPUDA?si=OaE7kf1xQnx0Wv_W) | [L12 // Слайды](../slides/s12.html) | [L12 // Конспект](../lectures/l12.html) | [Q12](https://forms.gle/nyFiewL3TT7RGurX8) |
| L13 // Кластерный анализ | [L13 // Кластерный анализ](https://youtu.be/QSSorYVfN_0?si=8M5sy4O_lCQOTLA_) | [L13 // Слайды](../slides/s13.html) | [L13 // Конспект](../lectures/l13.html) | [Q13](https://forms.gle/uaXZBZgXXuMXChoLA)   |
| L14 // Анализ главных компонент и эксплораторный факторный анализ | [L14 // PCA & EFA](https://youtu.be/TG0EexYUm50?si=N-I3s6ZvtReQZW4v) | [L14 // Слайды](../slides/s14.html) | [L14 // Конспект](../lectures/l14.html) | [Q14](https://forms.gle/boeRWUuVSoDJA8Qb8)   |
| L15 // Конфирматорный факторный анализ | [L15 // CFA](https://youtu.be/8b6VGYEa1PE?si=hST1iwDR_UW_l5IA) | [L15 // Слайды](../slides/s15.html) | [L15 // Конспект](../lectures/l15.html) | [Q15](https://forms.gle/774QEaizLEpn9JZr9)   |



## Практики // Домашки // Разборы

* [Плейлист с практиками](https://www.youtube.com/playlist?list=PL3GWEmQN96bvr2inm-16zHARgGoCY0n4F)
* [Книжка с заданиями практик](../practice/)
* [Книжка с заданиями домашек](../homeworks/)
* [Плейлист с разборами](https://www.youtube.com/playlist?list=PL3GWEmQN96bvT5WQ45rxUgj3L2DMSJ-E3)

| Практики  | Записи      | Задания      | Скрипты     | Домашки | Разборы | Скрипты     |
|-----------|-------------|--------------|-------------|---------|--------------|-------------|
| P1 // Введение в R. Типы данных. Векторы  | [P1 // Запись](https://youtu.be/GMTZkm_UljY?si=oQr6_4pZw14vl-jY)  | [P1 // Задания](../practice/pr1.html)  | [P1 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr1-course.R)  | [HW1](../homeworks/hw1.html)     | [A1 // Запись](https://youtu.be/2vV-OEIaVqQ)   | [A1 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw1.R)  |
| P2 // Матрицы и списки. Функции и строки  | [P2 // Запись](https://youtu.be/y6aaGoTTAFY?si=Sy_FKqVxQ2d8uy6z)  | [P2 // Задания](../practice/pr2.html)  | [P2 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr2-course.R)  | [HW2](../homeworks/hw2.html)     | [A2 // Запись](https://youtu.be/PlCW18I6ZcA)   | [A2 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw2.R)  |
| P3 // Датафреймы. Исследование данных. Дата и время  | [P3 // Запись](https://youtu.be/yHKhhJQpEbY?si=GW6QGreidXPTD9qw)  | [P3 // Задания](../practice/pr3.html)  | [P3 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr3-course.R)  | [HW3](../homeworks/hw3.html)     | [A3 // Запись](https://youtu.be/WoffShoneY8)   | [A3 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw3.R)  |
| P4 // Предобработка данных. Строки  | [P4 // Запись](https://youtu.be/pzdOFyx8o7A?si=hbMb5vFVovoOHn-D)  | [P4 // Задания](../practice/pr4.html)  | [P4 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr4-course.R)  | [HW4](../homeworks/hw4.html)     | [A4 // Запись](https://youtu.be/Rj3aB7mF-Lo)   | [A4 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw4.R)  |
| P5 // Визуализация данных  | [P5 // Запись](https://youtu.be/8Cdf3uaEuO0?si=gQaK6290F2YUHd-_)  | [P5 // Задания](../practice/pr5.html)  | [P5 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr5-course.R)  | [HW5](../homeworks/hw5.html)     | [A5 // Запись](https://youtu.be/rcnYRGX39gE)   | [A5 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw5.R)  |
| P6 // Математика и теория измерений  | Не состоялась  |  |  |  |  |
| P7 // Случайный эксперимент. Случайные величины  | [P7 // Запись](https://youtu.be/q9GHCzk0PhA?si=Iglhler36hFhCTiG)  | [P7 // Задания](../practice/pr7.html)  | [P7 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr7-course.R)  | [HW7](../homeworks/hw7.html)     | [A6 // Запись](https://youtu.be/5TESgYLlddQ)   | [A6 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw6.R)  |
| P8 // Оценивание статистических параметров. Тестирование статистических гипотез  | [P8 // Запись](https://youtu.be/x-D5blhaurU?si=sm0Q-ATDfk_3LEn1)  | [P8 // Задания](../practice/pr8.html)  | [P8 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr8-course.R)  | [HW8](../homeworks/hw8.html)     | [A7 // Запись](https://youtu.be/aDBtsEIeXhQ)   | [A7 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw7.R)  |
| P9 // Описательные статистики. Корреляционный анализ  | [P9 // Запись](https://youtu.be/cv1ck5Tg9Us?si=yalCaNw5JI3781DI)  | [P9 // Задания](../practice/pr9.html)  | [P9 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr9-course.R)  | [HW9](../homeworks/hw9.html)     | [A8 // Запись ](https://youtu.be/1cITe3r8Oyw)  | [A8 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw8.R)  |
| P10 // Простая линейная регрессия. Множественная линейная регрессия | [P10 // Запись](https://youtu.be/GnvjLxdBD-U?si=K0hx72NG6SNdaV-L) | [P10 // Задания](../practice/pr10.html) | [P10 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr10-course.R) | [HW10](../homeworks/hw10.html)    | [A9 // Запись](https://youtu.be/krjjYGrHOxQ)  | [A9 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw9.R) |
| P11 // Дисперсионный анализ. Ковариационный анализ | [P11 // Запись](https://youtu.be/ZcYeQvKm-Ls?si=R38A-ParoAKoXglh) | [P11 // Задания](../practice/pr11.html) | [P11 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr11-course.R) | [HW11](../homeworks/hw11.html)    | [A10 // Запись](https://youtu.be/4jxV6FRftrs)  | [A10 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw10.R) |
| P12 // Логистическая регрессия. Пуассоновская регрессия | [P12 // Запись](https://youtu.be/ZcYeQvKm-Ls?si=R38A-ParoAKoXglh) <br> [Вольный разговор за ML и GLM](https://youtu.be/Kq1_eZBYpUA?si=j9lJWMhFZm5bMUBc) | [P12 // Задания](../practice/pr12.html) | [P12 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr12-course.R) | [HW12](../homeworks/hw12.html)    | [A11 // Запись](https://youtu.be/9S5EEKqQWpo)  | [A11 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw11.R) |
| P13 // Регуляризованная регрессия. Обобщенные аддитивные модели | [P13 // Запись](https://youtu.be/1jkM5EM-7j0?si=9qEWKXFbbm2IP7AE) | [P13 // Задания](../practice/pr13.html) | [P13 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr13-course.R) | [HW13](../homeworks/hw13.html)    | [A12 // Запись](https://youtu.be/vyHhq2DUdwE)  | [A12 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw12.R) |
| P14 // GLMM для количественных переменных. GLMM для бинарных переменных | [P14 // Запись](https://youtu.be/O-X2aOv6s2Y?si=O4dLBw1bq3IL00qO) | [P14 // Задания](../practice/pr14.html) | [P14 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr14-course.R) | [HW14](../homeworks/hw14.html)    | [A13 // Запись](https://youtu.be/_oObY1q2vME)  | [A13 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw13.R) |
| P15 // Четкая кластеризация. Нечеткая кластеризация | [P15 // Запись](https://youtu.be/PQRl84ZqHUA?si=k4QyaXdC_72wJobl) | [P15 // Задания](../practice/pr15.html) | [P15 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr15-course.R) | [HW15](../homeworks/hw15.html)    | [A14 // Запись](https://youtu.be/2VKWG0aFDx0)  | [A14 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw14.R) |
| P16 // PCA. EFA | [P16 // Запись](https://youtu.be/f2IKC1nHtsA?si=Y7BSABhhZ6PutKox) | [P16 // Задания](../practice/pr16.html) | [P16 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr16-course.R) | [HW16](../homeworks/hw16.html)    | [A15 // Запись](https://youtu.be/dXH2J73ThRM)  | [A15 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw15.R) |
| P17 // CFA. Итоги | [P17 // Запись](https://youtu.be/nqvBFGxQx6s?si=gaSMkvurmj1cdHNz) | [P17 // Задания](../practice/pr17.html) | [P17 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/pr/scripts/pr17-course.R) | [HW17](../homeworks/hw17.html)    | [A16 // Запись](https://youtu.be/3H6dyXtWvp8)  | [A16 // Скрипт](https://github.com/angelgardt/wlm2023/blob/master/hw/solutions/hw16.R) |


## Проекты

* [Промежуточный проект](../projects/j.html)
* [Итоговый проект](../projects/f.html)
