---
title: "Что это?"
---

## О проекте

Курс «WLM 2023: анализ данных и машинное обучение для исследователей» проводился с ноября 2023 по апрель 2024 года. Здесь собраны все материалы --- лекции, практики, разборы, квизы, домашки, проекты --- созданные для него. Всё опубликовано в открытом доступе и может быть свободно использовано в некоммерческих целях. 

<!---
Также была написана расширенная [книжка](https://angelgardt.github.io/wlm-sdarp/).
--->

## Кто это сделал?

Идея и методическая разработка курса принадлежит [Антону Ангельгардту](https://angelgardt.github.io).

В разработке и проведении участвовали Илья Нартов, Владислав Поздеев, Ник Клименков, Екатерина Мартынова и Анастасия Шишунова.

Программу курса рецензировала Алмара Кулиева.

Экспертами курса были Елена Рыбина и Артур Аммалайнен.

И всё это было бы не возможно без незримого, но крайне важного участия многих представителей научного сообщества, которые когда-то заинтересовали, поддержали, поделились идеями и знаниями и просто были рядом. Всем им --- Марии Чумаковой, Елене Горбуновой, Евгению Осину, Ивану Позднякову, Гарику Морозу, Денису Федерякину, Наталье Тюриной и многим-многим другим.

Всем так или иначе прикоснувшимся к курсу огромное спасибо!
