# Элементы теории множеств {#math-settheory}

## Множества и подмножества {#math-settheory-set}

### Принадлежность элемента множеству {#math-settheory-set-in}

### Включение {#math-settheory-set-include}

## Операции над множествами {#math-settheory-operations}

### Пересечение {#math-settheory-operation-intersection}

### Объединение {#math-settheory-operation-union}

### Дополнение {#math-settheory-operation-add}

### Разность {#math-settheory-operation-diff}

### Декартово произведение {#math-settheory-operation-decart}

#### Координатная плоскость {#math-settheory-operation-coordplane}

### Power set {#math-settheory-operation-powerset}
как это называется по-русски????

### Разбиение множества {#math-settheory-operation-class}

## Отображения {#math-settheory-mapping}

### Инъекция {#math-settheory-mapping-injection}

### Сюръекция {#math-settheory-mapping-surjection}

### Биекция {#math-settheory-mapping-bijection}
    
### Отображения и функции {#math-settheory-mapping-functions}

## Пространства {#math-settheory-mapping-spaces}

