# Структуры данных {#rdstructs}
::: {.lab-chapter .lab-junior}
:::

Здесь мы познакомимся со структурами данных базового R. На них базируются все остальные структуры данных, с которыми ма когда-то столкнемся.

## Векторы {#rdstructs-vectors}
::: {.lab-chapter .lab-junior}
:::

### Создание векторов {#rdstructs-vectors-creation}

### Генерация числовых последовательностей {#rdstructs-vectors-sequences}

### Индексация векторов {#rdstructs-vectors-indexing}

### Операции над векторами {#rdstructs-vectors-manipulations}


## Матрицы {#rdstructs-matrices}
::: {.lab-chapter .lab-junior}
:::

### Создание матриц {#rdstructs-matrices-creation}

### Индексация матриц {#rdstructs-matrices-indexing}

### Операции над матрицами {#rdstructs-matrices-manipulations}


## Массивы {#rdstructs-arrays}
::: {.lab-chapter .lab-senior}
:::

## Списки {#rdstructs-lists}
::: {.lab-chapter .lab-junior}
:::

### Создание списков {#rdstructs-lists-creation}

### Индексация списков {#rdstructs-lists-indexing}

### Операции над списками {#rdstructs-lists-manipulations}

подумать, куда это деть, мб вынести в функции или куда-то еще, потому что тут просится map()


## Датафреймы {#rdstructs-dataframes}
::: {.lab-chapter .lab-junior}
:::

### Датафрейм как производное матрицы и списка {#rdstructs-dataframes-list-matris-child}

### Создание датафреймов {#rdstructs-dataframes-creation}

### Индексация датафреймов {#rdstructs-dataframes-indexing}

