# Обозначения {#book_signs .unnumbered}

## Лейблы {#book_labels .unnumbered}

В каждой главе на разделах и подразделах стоят лейблы, которые маркируют уровень сложности материала:

::: {.lab-chapter .lab-junior}
:::

Для начинающих и тех, кто пока не чувствует себя уверенно в самых основах.

::: {.lab-chapter .lab-middle}
:::

Для тех, кто разобрался с основами и хочет пойти дальше.

::: {.lab-chapter .lab-senior}
:::

Для тех, кто уверенно себя чувствует в материале и хочет разбираться в деталях.

::: {.lab-chapter .lab-guru}
:::

Для тех, кто преисполнился и хочет жести.


## Блоки {#book_callouts .unnumbered}

::: {.callout-note title="Заметка"}
Здесь написано что-то интересное. Почитайте на досуге.
:::

::: {.callout-warning title="Важно"}
Тут написано что-то важное. Обратите на этот блок внимание.
:::

::: {.callout-caution title="Caution with Title"}
Это пока не знаю что, мб его не использовать
:::

::: {.callout-important title="Важно!"}
Тут написано что-то очень важное! Обратите на этот блок пристальное внимание!
:::

::: {.callout-tip title="Совет"}
Здесь советы из собственного опыта. Возможно, они вам пригодятся.
:::



## Задания {#book_tasks .unnumbered}

::: {.task .question}
Это вопрос, который позволит вспомнить предыдущий материал или немного глубже копнуть в текущую тему. Как правило, имеющихся знаний будет достаточно для ответа на него, но иногда придётся и погуглить.
:::

::: {.task .math}
Это задание, где нужно что-то посчитать. Можно с помощью кода, а можно и руками.
:::

::: {.task .code}
Это задание, в котором надо написать код или посчитать что-то с помощью кода.
:::



## Символы {#book_symbols .unnumbered}

{{< include _symbols.qmd >}}

- $\setN$ --- множество натуральных чисел
- $\setNo$ --- множество натуральных чисел, включая ноль
- $\setZ$ --- множество целых чисел
- $\setQ$ --- множество рациональных чисел
- $\setR$ --- множество вещественных (действительных) чисел
- $\setC$ --- множество комплексных чисел

- $\alpha, \beta, \gamma, \dots$ --- числа, коэффициенты
- $X, Y, Z$ --- случайные величины
- $x, y, z$ --- числа, значения случайной величины
- $\vm a, \vm b, \vm c, \dots, \vm x, \vm y, \vm z$ --- векторы
- $\vm A, \vm B, \vm C, \dots, \vm X, \vm Y, \vm Z$ --- матрицы

- $\prob$ --- вероятность

- $\sum$ --- сумма
- $\prod$ --- произведение

- $\def$ --- равно по определению
