# Случайные величины {#stats-rand-values}

## Дискретные случайные величины {#stats-rand-values-discrete}

### Распределение дискретной случайной величины {#stats-rand-values-discrete-distribution}


## Непрерывные случайные величины {#stats-rand-values-continuous}

### Распределение непрерывной случайной величины {#stats-rand-values-continuous-distribution}


## Характеристики распределения случайный величин {#stats-rand-values-moments}


## Распределения случайных величин {#stats-rand-values-distributions}

### Распределение Бернулли {#stats-rand-values-bernoulli}

### Биноминальное распределение {#stats-rand-values-binom}

### Распределение Пуассона {#stats-rand-values-pois}

### Экспоненциальное распределение {#stats-rand-values-exp}

### Равномерное распределение {#stats-rand-values-uniform}

### Нормальное распределение {#stats-rand-values-norm}

### Геометрическое распределение {#stats-rand-values-geom}

### Отрицательное биномиальное распределение {#stats-rand-values-negbinom}


