# Введение в статистику {#stats-intro}

**Статистика** --- это междисциплинарная область знаний, а также практической деятельности, изучающая массовые явления, а также прицнипи и методы работы с данными, характеризующими эти явления.

Звучит красиво. Осталось понять, что это значит.

Массовые явления затрагивают огромные массы людей. Огромность масс, конечно, различна. Скажем, базовые перцептивные закономерности, связанные с тем, как устроена зрительная система, охватывают _всех людей_. Уровень удовлетворенности жизнью россиян охватывает только _население России_. Городские блага москвичей --- только для _жителей Москвы_. Учебная мотивация студентов департамента психологии НИУ ВШЭ --- это только про _людей с психологических бакалариата и магистратур НИУ ВШЭ_.

**Генеральная совокупность** --- множество всех [существующих] исследуемых объектов, а также сведения о них.

**Объем совокупности** ($N$) --- число единиц, образующих совокупность.

Короче, надо исследовать много людей, а времени и денег нет. Приходится из генеральной совокупности извлекать **выборку** --- некоторую часть нашей генеральной совокупности (объемом $n$). При этом $n \ll N$ (много меньше).

Нас, конечно же, интересуют какие-то **признаки**, которыми обладают объект нашей генеральной совокупности. Эти признаки могут быть выражены количественно в определенных **показателях**.

Например,

ТАБЛИЦА

Признаки могут быть очень разными, как и показатели, которыми мы их пытаемся измерить. Это мы рассмотрим в [теории измерений](#measurements-social-sci).

Что нам важно сейчас: генеральная совокупность характеризуется _параметром_.

**Параметр** --- относительно постоянная [от одной совокупности к другой] величина, характеризующая генеральную совокупность по некоторому показателю.

Ну, то есть в принципе существует _средний уровень нейротизма по BFI студента-психолога_ или _индекс индивидуализма/коллетивизма для конкретной культуры_. Проблема в том, что **величина параметра, который мы изучаем, неизвестна**. И никогда не будет известна.

Но почему?

- Мы не можем изучать всю генеральную совокупность --- слишком много объектов
- Наши измерения всегда содержат ошибку --- мы даже длину линейкой точно не можем измерить, что уж о психологических измерениях говорить

Поэтому величину параметра мы можем только предсказать с определённой статистической точностью. Измеряя что-либо на выборке, мы получаем **выборочную характеристику (оценку)** --- эмпирический (измеримый) аналог параметра.

## Задачи статистики {#stats-goals}

Мы в какой-то малоприятной ситуации… Мы пытаемся измерить то, что в определенном смысле невозможно измерить, при этом достаточно точно, чтобы потом это можно было сравнивать или строить какие-то модели. Задача выглядит заведомо провальной…

Однако именно в этот момент на помощь нам приходит статистика. Не в гордом одиночестве, конечно. Она проводит с собой теорию измерений, психометрику, теорию обнаружения сигнала и др. Всё это работает в нашей психологической науке в комлексе. Мы же в данном курсе сосредотачиваемся на статистической части этого салата.

Статистика даёт на теоретический и математический инструментарий, чтобы мы могли делать какие-либо выводы по нашим собранным данным. К сожалению, как бы нам не хотелось, мы не можем делать выводы по сырым данным, потому что измерения по выборке не отражают вот прям ровно то, что есть в генеральной совокупности. Нам их надо определенным образом обсчитать, чтобы наши выводы были корректными. Этим и занимается статистика.

Возможно, это звучит достаточно абстрактно, но я хочу, чтобы на данном моменте вы поймали некоторое интуитивное понимание того, зачем нужна статистика. Далее это обрастёт содержанием и уложится, я надеюсь, в достаточно стройную систему.

::: {.callout-warning title="Важно"}
Статистика помогает нам делать выводы о нашей генеральной совокупности по выборке.
:::

## Исследование с точки зрения статистики {#stats-research}

### Генеральная совокупность и выборка {#stats-population-sample}

### Параметр, индикатор, статистика {#stats-parameters}

### Исследовательский вопрос и гипотезы {#stats-hypotheses}


## Виды статистических данных {#stats-data}


## Виды статистики {#stats-kinds}

Cтатистика же как набор методов и инструментов делится на два вида:

- **Описательная статистика (descriptive statistics[^desc-stats-1])** занимается обработкой статистических данных, их наглядным представлением, и собственно описанием через некоторые характеристики.
  - Эти характеристики, количественно описывающие особенности имеющихся данных, называются **описательными статистиками (descriptive statistics[^desc-stats-2])**.
  - *Задача описательной статистики* --- ёмко описать имеющиеся данные и составить на основе этих описаний общее представление о них, а также обнаружить особенности, которые могут повлиять на дальнейший анализ.
- **Статистика вывода (inferential statistics)** занимается поиском ответов на содержательные вопросы, которые мы задаем данным в ходе их анализа в рамках научных и практических исследований.
  - Состоит из двух компонентов --- *тестирования статистических гипотез* и *статистических методов*.

[^desc-stats-1]: Mass (uncountable) noun
[^desc-stats-2]: Countable noun, plural in this case

::: {.task .question}
Ок, статистика вывода отвечает на вопросы, а описательная статистика описывает данные. А можно ли отвечать на вопросы с помощью описательной статистики?
:::

