<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>WLM 2023 - 24&nbsp; Описательные статистики</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./andan-ttest.html" rel="next">
<link href="./part-andan.html" rel="prev">
<link href="./pics/favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Ничего не найдено",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Очистить",
    "search-detached-cancel-button-title": "Отмена",
    "search-submit-button-title": "Отправить"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./pics/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">WLM 2023 // HSE UX LAB</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./../book/index.html">
 <span class="menu-text">Книга</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./../lectures/index.html">
 <span class="menu-text">Лекции</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./../practice/index.html">
 <span class="menu-text">Практики</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./../homeworks/index.html">
 <span class="menu-text">Домашки</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./../projects/index.html">
 <span class="menu-text">Проекты</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Описательные статистики</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Вступление</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./signs.html" class="sidebar-item-text sidebar-link">Обозначения</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">R</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Основы R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-dtypes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Типы данных</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-dstructs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Структуры данных</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-funcs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Функции</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-controlflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Управляющие конструкции</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Работа с данными</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Строки</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-dates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Дата и время</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-vis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Визуализация</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-tidy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Tidy Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><code>ggplot2</code></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Python</span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Математика для анализа данных</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math-logic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Элементы алгебры логики</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math-settheory.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Элементы теории множеств</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math-combinatorics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Элементы комбинаторики</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Элементы математического анализа</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math-linal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Элементы линейной алгебры</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Теория измерений</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./measurements-social-sci.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">measurements-social-sci.html</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./measurements-psychomentrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">measurements-psychomentrics.html</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Статистика для анализа данных</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats-intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Введение в статистику</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats-rand-exp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Случайный эксперимент</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats-rand-values.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Случайные величины</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats-estim.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Оценивание статистических параметров</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Тестирование статистических гипотез</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Методы анализа данных</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-descriptives.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Описательные статистики</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Сравнение средних</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-chisq.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Анализ категориальных данных</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Корреляционный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-nonparam.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Непараметрические методы анализа данных</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-simplelinear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Общие линейные модели. Простая линейная регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-multiplelinear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Множественная линейная регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-polynomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Полиномиальная регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-svr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Support Vector Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-regreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Регуляризованная регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Дисперсионный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Ковариационный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-manova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Многомерный дисперсионный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-treesreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Деревья решений. Регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-randforestreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Случайный лес. Регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Определение вида распределения переменной</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-logreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Обобщенные линейные модели. Логистическая регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-multinomlogreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Мультиномиальная логистическая регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-poissonreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Пуассоновская регрессия</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-glmm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Смешанные линейные модели</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-gam.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Обобщенные аддитивные модели</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Support Vector Machine</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-treesclass.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Деревья решений. Классификация</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-randforestclass.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Случайный лес. Классификация</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-cluster.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Кластерный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-lda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Линейный дискриминантный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Анализ главных компонент</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-ica.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Анализ независимых компонент</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-cca.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Анализ скоррелированных компонент</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-efa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Эксплораторный факторный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-sem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Моделирование структурными уравнениями</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-cfa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Конфирматорный факторный анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-path.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Путевой анализ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-timeseries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Основы анализа временных рядов</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Анализ данных в R</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-descriptives.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Описательные статистики в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Сравнение средних в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-chisq.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Анализ категориальных данных в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Корреляционный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-nonparam.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Непараметрические методы анализа данных в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-simplelinear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Общие линейные модели. Простая линейная регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-multiplelinear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Множественная линейная регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-polynomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Полиномиальная регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-svr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Support Vector Regression в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-regreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Регуляризованная регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Дисперсионный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Ковариационный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-manova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Многомерный дисперсионный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-treesreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Деревья решений. Регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-randforestreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Случайный лес. Регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Определение вида распределения переменной в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-logreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Обобщенные линейные модели. Логистическая регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-multinomlogreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Мультиномиальная логистическая регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-poissonreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Пуассоновская регрессия в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-glmm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Смешанные линейные модели в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-gam.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Обобщенные аддитивные модели в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./andan-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Support Vector Machine</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-treesclass.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Деревья решений. Классификация в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-randforestclass.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Случайный лес. Классификация в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-cluster.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Кластерный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-lda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Линейный дискриминантный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">Анализ главных компонент в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-ica.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Анализ независимых компонент в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-cca.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">86</span>&nbsp; <span class="chapter-title">Анализ скоррелированных компонент в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-efa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">87</span>&nbsp; <span class="chapter-title">Эксплораторный факторный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-sem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">88</span>&nbsp; <span class="chapter-title">Моделирование структурными уравнениями в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-cfa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">89</span>&nbsp; <span class="chapter-title">Конфирматорный факторный анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-path.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">90</span>&nbsp; <span class="chapter-title">Путевой анализ в R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randan-timeseries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">91</span>&nbsp; <span class="chapter-title">Основы анализа временных рядов в R</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Анализ данных в Python</span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Приложения</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">92</span>&nbsp; <span class="chapter-title">Числа и железо</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">93</span>&nbsp; <span class="chapter-title">Строки и железо</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_kilobytes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">94</span>&nbsp; <span class="chapter-title">Килобайты</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_memory.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">95</span>&nbsp; <span class="chapter-title">Память и процессор</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_proglang.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">96</span>&nbsp; <span class="chapter-title">Языки программирования</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_git.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">97</span>&nbsp; <span class="chapter-title">Git</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_formulas.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">98</span>&nbsp; <span class="chapter-title">Формулы</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">Источники</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Содержание</h2>
   
  <ul>
  <li><a href="#andan-descriptives-kinds-of-stats" id="toc-andan-descriptives-kinds-of-stats" class="nav-link active" data-scroll-target="#andan-descriptives-kinds-of-stats"><span class="toc-section-number">24.1</span>  Виды статистики</a></li>
  <li><a href="#andan-descriptives-central-tendency" id="toc-andan-descriptives-central-tendency" class="nav-link" data-scroll-target="#andan-descriptives-central-tendency"><span class="toc-section-number">24.2</span>  Меры центральной тенденции</a>
  <ul class="collapse">
  <li><a href="#andan-descriptives-mode" id="toc-andan-descriptives-mode" class="nav-link" data-scroll-target="#andan-descriptives-mode"><span class="toc-section-number">24.2.1</span>  Мода</a></li>
  <li><a href="#andan-descriptives-unimodal-bimodal" id="toc-andan-descriptives-unimodal-bimodal" class="nav-link" data-scroll-target="#andan-descriptives-unimodal-bimodal"><span class="toc-section-number">24.2.2</span>  Унимодальные и полимодальные распределения</a></li>
  <li><a href="#andan-descriptives-median" id="toc-andan-descriptives-median" class="nav-link" data-scroll-target="#andan-descriptives-median"><span class="toc-section-number">24.2.3</span>  Медиана</a></li>
  <li><a href="#andan-descriptives-mean" id="toc-andan-descriptives-mean" class="nav-link" data-scroll-target="#andan-descriptives-mean"><span class="toc-section-number">24.2.4</span>  Среднее</a></li>
  <li><a href="#andan-descriptives-mean-vs-median" id="toc-andan-descriptives-mean-vs-median" class="nav-link" data-scroll-target="#andan-descriptives-mean-vs-median"><span class="toc-section-number">24.2.5</span>  Среднее vs медиана</a></li>
  </ul></li>
  <li><a href="#andan-descriptives-variability" id="toc-andan-descriptives-variability" class="nav-link" data-scroll-target="#andan-descriptives-variability"><span class="toc-section-number">24.3</span>  Меры разброса</a>
  <ul class="collapse">
  <li><a href="#andan-descriptives-range" id="toc-andan-descriptives-range" class="nav-link" data-scroll-target="#andan-descriptives-range"><span class="toc-section-number">24.3.1</span>  Минимум, максимум, размах</a></li>
  <li><a href="#andan-descriptives-average-absolute-deviation" id="toc-andan-descriptives-average-absolute-deviation" class="nav-link" data-scroll-target="#andan-descriptives-average-absolute-deviation"><span class="toc-section-number">24.3.2</span>  Среднее абсолютное отклонение</a></li>
  <li><a href="#andan-descriptives-variance" id="toc-andan-descriptives-variance" class="nav-link" data-scroll-target="#andan-descriptives-variance"><span class="toc-section-number">24.3.3</span>  Дисперсия</a></li>
  <li><a href="#andan-descriptives-standard-deviation" id="toc-andan-descriptives-standard-deviation" class="nav-link" data-scroll-target="#andan-descriptives-standard-deviation"><span class="toc-section-number">24.3.4</span>  Стандартное отклонение</a></li>
  <li><a href="#andan-descriptives-quantiles" id="toc-andan-descriptives-quantiles" class="nav-link" data-scroll-target="#andan-descriptives-quantiles"><span class="toc-section-number">24.3.5</span>  Квантили</a></li>
  <li><a href="#andan-descriptives-quartiles" id="toc-andan-descriptives-quartiles" class="nav-link" data-scroll-target="#andan-descriptives-quartiles"><span class="toc-section-number">24.3.6</span>  Квартили</a></li>
  </ul></li>
  <li><a href="#andan-descriptives-skewness" id="toc-andan-descriptives-skewness" class="nav-link" data-scroll-target="#andan-descriptives-skewness"><span class="toc-section-number">24.4</span>  Асимметрия</a></li>
  <li><a href="#andan-descriptives-kurtosis" id="toc-andan-descriptives-kurtosis" class="nav-link" data-scroll-target="#andan-descriptives-kurtosis"><span class="toc-section-number">24.5</span>  Эксцесс</a></li>
  <li><a href="#andan-descriptives-final" id="toc-andan-descriptives-final" class="nav-link" data-scroll-target="#andan-descriptives-final"><span class="toc-section-number">24.6</span>  Итоги</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="andan-descriptives" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Описательные статистики</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lab-chapter lab-junior">

</div>
<div class="cell">

</div>
<!--- {{< include _symbols.qmd >}} --->
<!--- Number sets--->
<!--- Linear Algebra --->
<!--- vectors and matrices --->
<!--- Probability --->
<!--- Distributions --->
<!--- Other --->
<!--- Trig --->
<section id="andan-descriptives-kinds-of-stats" class="level2" data-number="24.1">
<h2 data-number="24.1" class="anchored" data-anchor-id="andan-descriptives-kinds-of-stats"><span class="header-section-number">24.1</span> Виды статистики</h2>
<div class="lab-chapter lab-junior">

</div>
<p>Напомним себе, что статистика [как набор методов и инструментов] делится на два вида — описательная статистика и статистика вывода.</p>
<ul>
<li><strong>Описательная статистика (descriptive statistics<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>)</strong> занимается обработкой статистических данных, их наглядным представлением, и собственно описанием через некоторые характеристики.
<ul>
<li>Эти характеристики, количественно описывающие особенности имеющихся данных, называются <strong>описательными статистиками (descriptive statistics<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>)</strong>.</li>
<li><em>Задача описательной статистики</em> — ёмко описать имеющиеся данные и составить на основе этих описаний общее представление о них, а также обнаружить особенности, которые могут повлиять на дальнейший анализ.</li>
</ul></li>
<li><strong>Статистика вывода (inferential statistics)</strong> занимается поиском ответов на содержательные вопросы, которые мы задаем данным в ходе их анализа в рамках научных и практических исследований.
<ul>
<li>Состоит из двух компонентов — <em>тестирования статистических гипотез</em> и <em>статистических методов</em>.</li>
</ul></li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body" title="Замечание о машинном обучении">
<p>В названии книги упомянуто «машинное обучение». Иногда его причисляют к статистике, иногда рассматривают отдельно. На самом же деле, статистические методы лежат где-то между статистикой вывода и машинным обучением.</p>
<p>Почему?</p>
<p>Дело в том, что на статистические методы можно смотреть по-разному.</p>
<ul>
<li>Если нашей задачей является поиск ответов на <strong>исследовательские</strong> вопросы о закономерностях, о связи каких-либо факторов или влиянии переменных друг на друга, то мы будем смотреть на статистические модели с точки зрения статистики вывода. Это позволит нам находить ответы на интересующие нас вопросы — причем не важно, говорим мы о научных исследованиях или об исследованиях в индустрии.</li>
<li>Если перед нами стоит задача хорошо <strong>предсказывать</strong> одни переменные на основании значений других — например, выдавать рекомендации на Яндекс.Музыке или в Яндекс.Лавке&nbsp;— то мы будем смотреть на те же статистические модели с точки зрения машинного обучения.</li>
</ul>
<p>То есть, модели в анализе данных и машинном обучении одни и те же, но то, какую модель мы назовем хорошей и как мы эту «хорошесть» определим, будет отличаться в зависимости от задачи&nbsp;— <em>исследовательская</em> или <em>предиктивная</em>&nbsp;— которая перед нами стоит.</p>
</div>
</div>
</section>
<section id="andan-descriptives-central-tendency" class="level2" data-number="24.2">
<h2 data-number="24.2" class="anchored" data-anchor-id="andan-descriptives-central-tendency"><span class="header-section-number">24.2</span> Меры центральной тенденции</h2>
<div class="lab-chapter lab-junior">

</div>
<p>Итак, мы хотим описать наши данные. Точнее, распределения переменных, которые у нас в данных есть. Хотим сделать это просто и ёмко. Насколько просто и ёмко? Ну, допустим максимально — одним числом. Для этого неплохо подойдет значение переменной, которое лежит <em>в центре</em> распределения.</p>
<p>Как мы будем искать, что там в центре распределения? Зависит от <a href="">шкалы</a> <span class="citation" data-cites="stevens46">(<a href="references.html#ref-stevens46" role="doc-biblioref">Stevens 1946</a>)</span>, в которой измерена конкретная переменная (<a href="#tbl-scales-cental-tendencies">Таблица&nbsp;<span>24.1</span></a>).</p>
<div id="tbl-scales-cental-tendencies" class="anchored">
<table class="table">
<caption>Таблица&nbsp;24.1: Шкалы и меры центральной тенденции</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Шкала</strong></th>
<th style="text-align: left;"><strong>Мера центральной тенденции</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><em>Номинальная</em></td>
<td style="text-align: left;">Мода</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>Порядковая</em></td>
<td style="text-align: left;">Медиана</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>Интервальная</em></td>
<td style="text-align: left;">Среднее арифметическое</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>Абсолютная</em></td>
<td style="text-align: left;">Среднее арифметическое, геометрическое и др.</td>
</tr>
</tbody>
</table>
</div>
<p>Однако есть некоторые нюансы.</p>
<section id="andan-descriptives-mode" class="level3" data-number="24.2.1">
<h3 data-number="24.2.1" class="anchored" data-anchor-id="andan-descriptives-mode"><span class="header-section-number">24.2.1</span> Мода</h3>
<div class="lab-chapter lab-junior">

</div>
<p>Самый простой вариант найти центральную тенденцию — это определить наиболее часто встречающееся значение переменной. Это значение называется <em>модой (mode)</em>.</p>
<div id="def-mode-discrete" class="theorem definition">
<p><span class="theorem-title"><strong>Определение 24.1 </strong></span><strong>Мода</strong> [дискретной переменной] — наиболее часто встречающееся значение данной переменной.</p>
</div>
<p>Например, у нас есть следующий ряд наблюдений по какой-то переменной:</p>
<p><span class="math display">\[
\begin{bmatrix}
1 &amp; 3 &amp; 4 &amp; 6 &amp; 3 &amp; 2 &amp; 3 &amp; 3 &amp; 2 &amp; 4 &amp; 1
\end{bmatrix}
\]</span></p>
<p>Если мы посчитаем, сколько раз встретилась каждое значение переменной и составим таблицу частот, то получим следующее:</p>
<p><span class="math display">\[
\begin{matrix}
\text{Значение} &amp; 1 &amp; 2 &amp; 3 &amp; 4 &amp; 6 \\
\text{Частота}  &amp; 2 &amp; 2 &amp; 4 &amp; 2 &amp; 1
\end{matrix}
\]</span></p>
<p>Очевидно, что <span class="math inline">\(3\)</span> встречается чаще других значений — это и есть мода.</p>
<p>Понятно, что если на нашей шкале нет чисел, а есть текстовые лейблы, это ничего не меняет. Пусть у нас есть переменная с кодами аэропортов:</p>
<p><span class="math display">\[
\begin{bmatrix}
\text{DME} &amp; \text{LED} &amp; \text{IST} &amp; \text{AER} &amp; \text{IST} &amp;\text{SVO} &amp; \text{LED} &amp; \text{VKO} &amp; \text{LED} &amp; \text{IST} &amp; \text{IST} &amp; \text{VKO} &amp; \text{AER} &amp; \text{DME}
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Значение} &amp; \text{DME} &amp; \text{LED} &amp; \text{IST} &amp; \text{AER} &amp; \text{SVO} &amp; \text{VKO}\\
\text{Частота}  &amp; 2 &amp; 3 &amp; 4 &amp; 2 &amp; 1 &amp; 2
\end{matrix}
\]</span></p>
<p>Мода — <span class="math inline">\(\text{IST}\)</span> (Международный аэропорт Стамбула, İstanbul Havalimanı).</p>
<p>Так мы действуем в случае с эмпирическим распределением. Если нам известна <a href="">функция вероятности переменной (probability mass function, PMF)</a>, то мы можем определить моду, основываясь на ней:</p>
<div id="def-mode-discrete-pmf" class="theorem definition">
<p><span class="theorem-title"><strong>Определение 24.2 </strong></span><strong>Мода</strong> [дискретной переменной] — это значение переменной, при котором её функция вероятности принимает своё максимальное значение.</p>
</div>
<p><span id="eq-mode-pmf"><span class="math display">\[
\text{mode}(X) = \arg \max(\text{PMF}(X)) = \arg \max_{x_i}(\mathbb{P}(X = x_i)),
\tag{24.1}\]</span></span></p>
<p>где <span class="math inline">\(X\)</span> — дискретная случайная величина, <span class="math inline">\(x_i\)</span> — значение этой случайной величины.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mode-pmf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-mode-pmf-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.1: Определение моды с помощью функции вероятности</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Окей, мы видим, что <em>мода отлично считается на дискретных переменных</em>. А как же быть с непрерывными?</p>
<p><a href="">Напомним себе</a>, что вероятность того, что непрерывная случайная величина примет своё конкретное значение, равна нулю. Из этого следует, что все значения непрерывной случайное величины уникальны — каждое повторяется только один раз. Получается, что строить частотную таблицу бессмысленно…</p>
<p>По этой причине <strong>для непрерывных переменных моду не считают</strong>.</p>
<section id="andan-descriptives-mode-contunious" class="level4" data-number="24.2.1.1">
<h4 data-number="24.2.1.1" class="anchored" data-anchor-id="andan-descriptives-mode-contunious"><span class="header-section-number">24.2.1.1</span> Мода для непрерывной переменной</h4>
<div class="lab-chapter lab-middle">

</div>
<p>Да, это так. Действительно, посчитать моду для непрерывной переменной способом, аналогичным тому, что мы увидели выше, не получится. Однако математиков это не остановило.</p>
<p>Если мы посмотрим на <a href="">график плотности вероятности</a> (probability density function, PDF), который является аналогом PMF для дискретных переменных, мы увидим, что какие-то значения встречаются чаще, а какие-то реже. Что в общем-то логично. Напомним себе, <a href="">как это выглядит</a>, например, для любимого [стандартного] <a href="">нормального распределения</a>:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-continuous-freqs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-continuous-freqs-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.2: Частоты интервалов значений непрерывной случайной величины на функции плотности распределения</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>То есть, самые часто встречающиеся значения — это <strong>пик распределения</strong>. Там и должна быть мода. Визуально это выглядит достаточно справедливо.</p>
<p>Математики так и решили:</p>
<div id="def-mode-continuous" class="theorem definition">
<p><span class="theorem-title"><strong>Определение 24.3 </strong></span><strong>Мода</strong> [непрерывной переменной] — это значение переменной, при котором её функция плотности вероятности достигает локального<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> максимума.</p>
</div>
<p><span id="eq-mode-pdf"><span class="math display">\[
\text{mode}(X) = \arg \max(\text{PDF}(X)) = \arg \max_{x \in S}f(x),
\tag{24.2}\]</span></span></p>
<p>гдe <span class="math inline">\(X\)</span> — непрерывная случайная величина, <span class="math inline">\(x\)</span> — значение этой случайной величины, <span class="math inline">\(S\)</span> — имеющаяся выборка значений переменной.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-continuous-mode" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-continuous-mode-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.3: Положение моды на функции плотности [стандартного] нормального распределения</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Хотя моду для непрерывной переменной вычислить можно, обычно этого не делают, так как достаточно других мер центральной тенденции для описания распределения.</p>
<hr>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body" title="Take-home: мода">
<ul>
<li>мода — это значение переменной, которое встречается в выборке чаще всего</li>
<li>на практике она рассчитывается через построение частотной таблицы</li>
<li>используется с дискретными (номинальными и порядковыми) переменными</li>
<li>для непрерывных переменных её рассчитать можно, но обычного этого не делают</li>
</ul>
</div>
</div>
</section>
</section>
<section id="andan-descriptives-unimodal-bimodal" class="level3" data-number="24.2.2">
<h3 data-number="24.2.2" class="anchored" data-anchor-id="andan-descriptives-unimodal-bimodal"><span class="header-section-number">24.2.2</span> Унимодальные и полимодальные распределения</h3>
<div class="lab-chapter lab-junior">

</div>
<p>Нормальное распределение, как и ряд других — биномиальное, отрицательное биномиальное, пуассоновское — относятся к <em>унимодальным</em>. Такие распределения имеют только <em>одну моду</em> (см. <a href="#fig-norm-mode">Рисунок&nbsp;<span>24.4</span></a>, <a href="#fig-binom-mode">Рисунок&nbsp;<span>24.5</span></a>, <a href="#fig-poiss-mode">Рисунок&nbsp;<span>24.6</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-norm-mode" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-norm-mode-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.4: Нормальное распределение (μ&nbsp;=&nbsp;2$, σ&nbsp;=&nbsp;0.5). Пунктирной линией обозначено положение моды.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-binom-mode" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-binom-mode-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.5: Биномиальное распределение (n&nbsp;=&nbsp;50, p&nbsp;=&nbsp;0.3). Пунктирной линией обозначено положение моды.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-poiss-mode" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-poiss-mode-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.6: Распределение Пуассона (λ&nbsp;=&nbsp;5.5). Пунктирной линией обозначено положение моды.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Это теоретические распределения. С эмпирическими распределениями дело обстоит так же, хотя они обычно менее гладенькие и красивые (см. <a href="#fig-mode-norm-sample">Рисунок&nbsp;<span>24.7</span></a> и <a href="#fig-mode-nbinom-sample">Рисунок&nbsp;<span>24.8</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mode-norm-sample" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-mode-norm-sample-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.7: Эмпирическое распределение, сгенерированное из нормального распределения (μ&nbsp;=&nbsp;8, σ&nbsp;=&nbsp;4, n&nbsp;=&nbsp;100). <code>set.seed(314)</code>. Пунктирной линией обозначено положение моды.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mode-nbinom-sample" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-mode-nbinom-sample-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.8: Эмпирическое распределение, сгенерированное из логнормального распределения (μ&nbsp;=&nbsp;1.1, σ&nbsp;=&nbsp;1.39, n&nbsp;=&nbsp;30). <code>set.seed(314)</code>. Пунктирной линией обозначено положение моды.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Однако на практике возможны и другие ситуации. Например, такие (<a href="#fig-bimodal">Рисунок&nbsp;<span>24.9</span></a>, <a href="#fig-polymodal">Рисунок&nbsp;<span>24.10</span></a>):</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bimodal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-bimodal-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.9: Бимодальное распределение. Сгенерировано из двух нормальных распределений (μ<sub>1</sub>&nbsp;=&nbsp;1.5, σ<sub>1</sub>&nbsp;=&nbsp;0.4, n<sub>1</sub>&nbsp;=&nbsp;80; μ<sub>2</sub>&nbsp;=&nbsp;4, σ<sub>2</sub>&nbsp;=&nbsp;0.5, n<sub>2</sub>&nbsp;=&nbsp;40). <code>set.seed(65)</code>. Пунктирными линиями обозначены положения мод.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-polymodal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-polymodal-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.10: Полимодальное распределение. Сгенерировано из двух нормальных распределений (μ<sub>1</sub>&nbsp;=&nbsp;1.5, σ<sub>1</sub>&nbsp;=&nbsp;0.3, n<sub>1</sub>&nbsp;=&nbsp;80; μ<sub>2</sub>&nbsp;=&nbsp;3.4, σ<sub>2</sub>&nbsp;=&nbsp;0.5, n<sub>2</sub>&nbsp;=&nbsp;40) и бета-распределения (α&nbsp;=&nbsp;2, β&nbsp;=&nbsp;4, n&nbsp;=&nbsp;50). <code>set.seed(65)</code>. Пунктирными линиями обозначены положения мод.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>В первом случае (<a href="#fig-bimodal">Рисунок&nbsp;<span>24.9</span></a>) мы видим <em>два локальных максимума</em> функции плотности вероятности — такое распределение называется <strong>бимодальным</strong>. Во втором случае (<a href="#fig-polymodal">Рисунок&nbsp;<span>24.10</span></a>) функция плотности вероятности имеет <em>три локальных максимума</em> — такое распределение называется <strong>полимодальным</strong>. Бимональное распределение является частным случаем полимодального распределения.</p>
<p>В прицнипе, пиков может быть и больше, однако при работе с реальными данными чаще всего мы сталкиваемся с бимодальными распределениями.</p>
<p><strong>Что это значит и что с этим делать?</strong></p>
<p>Бимодальное распределение сигнализирует нам о <strong>гетерогенности выборки</strong>. Если мы видим два выделяющихся пика, стоит подумать о том, что наша выборка неоднородна и в ней выделяются две подвыборки. Посмотрим на структуру выборки из примера выше (<a href="#fig-bimodal-struct">Рисунок&nbsp;<span>24.11</span></a>):</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bimodal-struct" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-bimodal-struct-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.11: Структура бимодального распределения из <a href="#fig-bimodal">Рисунок&nbsp;<span>24.9</span></a>. Для удобства сопоставления графиков плотностей вероятности по оси ординат отложены частоты.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Действительно, наше распределение состоит из двух других распределений, у каждого из которого есть своя мода — поэтому итоговое распределение получается бимодальным. Конечно, сейчас нам это очень удобно показать, потому что мы знаем, как это распределение генерировалось. Когда же у нас есть реальные данные и мы там наблюдаем такого «верблюда», бывает достаточно сложно сказать, что «пошло не так».</p>
<p>Само по себе распределение не даст нам ответ на вопрос, почему оно бимодальное — чтобы выяснить причины такого поведения переменной нам потребуются другие данные. Обычно у вас в данных есть «соцдем» — пол, возраст, сфера и место работы, уровень обрвазования и др. Попробуйте построить распределение с разбиением исследуемой бимодальной переменной по переменным «соцдема». Это, к сожалению, не является рецептом успеха, поскольку причина гетерогенности выборки может и не содержаться в ваших данных, но такое изучение данных станет хорошим показателем того, что вы не просто «забили» на странное распределение своей переменной, а поисследователи возможные его причины.</p>
<p>Если вам удалось найти причины гетерогенности выборки — допустим, у вас выделяются подвыборки «бакалавры» и «магистры» — стоит подумать о том, как обойтись с этой переменной в планируемом анализе, так как игнорировать её, по-видимому, нельзя, поскольку она влияет на вариатиность данных.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body" title="Соцдем лишним не бывает">
<p>На этапе планирования исследования подумайте о том, чем могут отличаться ваши респонденты или испытуемые между собой, помимо индивидуальных различий.</p>
<ul>
<li>Если в эксперименте используете задачу мысленного вращения (mental rotation, <span class="citation" data-cites="shepard71">(<a href="references.html#ref-shepard71" role="doc-biblioref">Shepard and Metzler 1971</a>)</span>), вполне возможно, испытуемые, работающие в сфере 3D-моделирования или дизайна интерьеров, могут сформировать подвыборку.</li>
<li>В случае HR-исследования, где фиксируется доход респондента, необходимо записать город, в котором он проживает и/или работает.</li>
<li>При изучении удовлетворенности городским пространством важными пунктами станут беременность, наличие/отсутствие детей, наличие/отсутствие автомобиля и др.</li>
</ul>
<p>И так далее. Примеров для каждого случая можно подобрать много.</p>
<p>Стоит ли, скажем, в первом случае сразу исключить из выборки 3D-моделлеров? Зависит. От количества времени и денег на проведение исследования. Однако <em>как минимум эту информацию надо зафиксировать в данных</em>. А решить, исключать ли этих респондентов из выборки или нет, можно и позже. Главно об этом написать в отчете/статье, когда будете описывать предобработку данных.</p>
</div>
</div>
<hr>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body" title="Take-home: бимодальное распределение">
<ul>
<li>бимодальное распределение намекает на неоднородность данных — скорее всего, в выборке есть две подвыборки</li>
<li>необходимо поискать в данных причины этой неодноросности, например, в социально-демографических переменных</li>
<li>если удалось найти переменную, объясняющую бимодальность, стоит подумать о том, как её учитывать в планируемом анализе</li>
</ul>
</div>
</div>
</section>
<section id="andan-descriptives-median" class="level3" data-number="24.2.3">
<h3 data-number="24.2.3" class="anchored" data-anchor-id="andan-descriptives-median"><span class="header-section-number">24.2.3</span> Медиана</h3>
<div class="lab-chapter lab-junior">

</div>
<p>Для номинальной шкалы мода — это единственно возможная мера центральной тенденции, потому что на этой шкале отсутствует порядок элементов. На других шкалах наблюдения уже можно сортировать по возрастнию или убыванию, поскольку начиная с ранговой (порядковой) шкалы на всех них определена операция сравнения на «больше-меньше».</p>
<p>Возьмем тот же ряд наблюдений, что и в предыдущем разделе:</p>
<p><span class="math display">\[
\begin{bmatrix}
1 &amp; 3 &amp; 4 &amp; 6 &amp; 3 &amp; 2 &amp; 3 &amp; 3 &amp; 2 &amp; 4 &amp; 1
\end{bmatrix}
\]</span></p>
<p>Отсортируем наблюдения по возрастанию:</p>
<p><span class="math display">\[
\begin{bmatrix}
1  &amp; 1 &amp; 2 &amp; 2 &amp; 3 &amp; 3 &amp; 3 &amp; 3 &amp; 4 &amp; 4 &amp; 6
\end{bmatrix}
\]</span></p>
<p>Наша задача — определить центральную тенденцию. Давайте посмотрим, что оказалось в середине отсортированного ряда:</p>
<p><span class="math display">\[
\begin{bmatrix}
1 &amp; 1 &amp; 2 &amp; 2 &amp; 3 &amp; \mathbf{3} &amp; 3 &amp; 3 &amp; 4 &amp; 4 &amp; 6
\end{bmatrix}
\]</span></p>
<p>Это медиана. В данном случае она равна <span class="math inline">\(3\)</span>.</p>
<div id="def-median" class="theorem definition">
<p><span class="theorem-title"><strong>Определение 24.4 </strong></span><strong>Медиана (median)</strong> — это значение, которое располагается на середине отсортированного ряда значений переменной.</p>
</div>
<p>Медиана делит все наблюдения переменной ровно пополам и половина наблюдений оказывается по одну сторону от медианы, а половина — по другую.</p>
<p>Если число наблюдений нечётное, то всё ясно — в середине отсортированного ряда будет какое-то значение. А если число наблюдений чётное? Тогда мы попадаем между значениями.</p>
<p>Возьмем для примера такой вектор наблюдений:</p>
<p><span class="math display">\[
\begin{bmatrix}
14 &amp; 10 &amp; 9 &amp; 16 &amp; 30 &amp; 3 &amp; 25 &amp; 8 &amp; 18 &amp; 7
\end{bmatrix}
\]</span></p>
<p>Отсортируем:</p>
<p><span class="math display">\[
\begin{bmatrix}
3 &amp; 7 &amp; 8 &amp; 9 &amp; 10 &amp; 14 &amp; 16 &amp; 18 &amp; 25 &amp; 30
\end{bmatrix}
\]</span></p>
<p>Найдем середину:</p>
<p><span class="math display">\[
\begin{bmatrix}
3 &amp; 7 &amp; 8 &amp; 9 &amp; 10 &amp; | &amp; 14 &amp; 16 &amp; 18 &amp; 25 &amp; 30
\end{bmatrix}
\]</span></p>
<p>В таком случае в качестве медианы берется среднее между двумя срединными значениями:</p>
<p><span class="math display">\[
\text{median} = \frac{10 + 14}{2} = 12
\]</span></p>
<p>Итого, формализовать вычисление медианы можно следующим образом:</p>
<p><span id="eq-median-formula"><span class="math display">\[
\text{median}(X) = X(a) =
\cases{
X\left(\frac{n+1}{2}\right), &amp; if  2&nbsp;|&nbsp;n \\
\dfrac{X(\frac{n}{2}) + X(\frac{n}{2} + 1)}{2}, &amp; otherwise
}
\tag{24.3}\]</span></span></p>
<p>где <span class="math inline">\(X\)</span> — ряд наблюдений случайной величины, <span class="math inline">\(n\)</span> — число наблюдений, <span class="math inline">\(X(a)\)</span> — наблюдение с индексом <span class="math inline">\(a\)</span> в отсортированном векторе <span class="math inline">\(X\)</span>.</p>
<p>Если мы будем смотреть на медиану с позиции описания распределения, то она будет той самой линией, которая разделит площадь под графиком функции плотности вероятности пополам:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-median-norm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-median-norm-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.12: Медиана нормального распределения</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>При этом форма распределения не имеет значения — площадь под графиком всегда будет делиться пополам:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-median-left-skew" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-median-left-skew-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.13: Медиана распределения с отрицательной асимметрией.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-median-right-skew" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-median-right-skew-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.14: Медиана распределения с положительной асимметрией.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-median-bimodal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="andan-descriptives_files/figure-html/fig-median-bimodal-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Рисунок&nbsp;24.15: Медиана бимодального распределения.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body" title="Take-home: медиана">
<ul>
<li>медиану можно расчитать только на шкалах, где задан порядок (ранговая, интервальная, абсолютная)</li>
<li>медиана делит выборку наблюдений на две равные части</li>
<li>линия медианы раздели площадь под графиком функции плотности вероятности пополам</li>
</ul>
</div>
</div>
</section>
<section id="andan-descriptives-mean" class="level3" data-number="24.2.4">
<h3 data-number="24.2.4" class="anchored" data-anchor-id="andan-descriptives-mean"><span class="header-section-number">24.2.4</span> Среднее</h3>
<div class="lab-chapter lab-junior">

</div>
<section id="andan-descriptives-arithmetic-mean" class="level4" data-number="24.2.4.1">
<h4 data-number="24.2.4.1" class="anchored" data-anchor-id="andan-descriptives-arithmetic-mean"><span class="header-section-number">24.2.4.1</span> Арифметическое среднее</h4>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-trimmed-mean" class="level4" data-number="24.2.4.2">
<h4 data-number="24.2.4.2" class="anchored" data-anchor-id="andan-descriptives-trimmed-mean"><span class="header-section-number">24.2.4.2</span> Усеченное среднее</h4>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-geometric-mean" class="level4" data-number="24.2.4.3">
<h4 data-number="24.2.4.3" class="anchored" data-anchor-id="andan-descriptives-geometric-mean"><span class="header-section-number">24.2.4.3</span> Геометрическое среднее</h4>
<div class="lab-chapter lab-middle">

</div>
</section>
<section id="andan-descriptives-quandratic-mean" class="level4" data-number="24.2.4.4">
<h4 data-number="24.2.4.4" class="anchored" data-anchor-id="andan-descriptives-quandratic-mean"><span class="header-section-number">24.2.4.4</span> Квадратичное среднее</h4>
<div class="lab-chapter lab-middle">

</div>
</section>
<section id="andan-descriptives-harmonic-mean" class="level4" data-number="24.2.4.5">
<h4 data-number="24.2.4.5" class="anchored" data-anchor-id="andan-descriptives-harmonic-mean"><span class="header-section-number">24.2.4.5</span> Гармоническое среднее</h4>
<div class="lab-chapter lab-middle">

</div>
</section>
<section id="andan-descriptives-weighted-mean" class="level4" data-number="24.2.4.6">
<h4 data-number="24.2.4.6" class="anchored" data-anchor-id="andan-descriptives-weighted-mean"><span class="header-section-number">24.2.4.6</span> Взвешенное среднее</h4>
<div class="lab-chapter lab-junior">

</div>
</section>
</section>
<section id="andan-descriptives-mean-vs-median" class="level3" data-number="24.2.5">
<h3 data-number="24.2.5" class="anchored" data-anchor-id="andan-descriptives-mean-vs-median"><span class="header-section-number">24.2.5</span> Среднее vs медиана</h3>
<div class="lab-chapter lab-junior">

</div>
<p>Помимо того, что среднее и медиана информативны сами по себе, полезно смотреть на их взаимное расположение.</p>
<p>ПРОДОЛЖИТЬ</p>
</section>
</section>
<section id="andan-descriptives-variability" class="level2" data-number="24.3">
<h2 data-number="24.3" class="anchored" data-anchor-id="andan-descriptives-variability"><span class="header-section-number">24.3</span> Меры разброса</h2>
<div class="lab-chapter lab-junior">

</div>
<section id="andan-descriptives-range" class="level3" data-number="24.3.1">
<h3 data-number="24.3.1" class="anchored" data-anchor-id="andan-descriptives-range"><span class="header-section-number">24.3.1</span> Минимум, максимум, размах</h3>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-average-absolute-deviation" class="level3" data-number="24.3.2">
<h3 data-number="24.3.2" class="anchored" data-anchor-id="andan-descriptives-average-absolute-deviation"><span class="header-section-number">24.3.2</span> Среднее абсолютное отклонение</h3>
<div class="lab-chapter lab-middle">

</div>
<section id="andan-descriptives-mean-absolute-deviation-around-the-mean" class="level4" data-number="24.3.2.1">
<h4 data-number="24.3.2.1" class="anchored" data-anchor-id="andan-descriptives-mean-absolute-deviation-around-the-mean"><span class="header-section-number">24.3.2.1</span> Среднее абсолютное отклонение от среднего</h4>
<div class="lab-chapter lab-middle">

</div>
</section>
<section id="andan-descriptives-mean-absolute-deviation-around-the-median" class="level4" data-number="24.3.2.2">
<h4 data-number="24.3.2.2" class="anchored" data-anchor-id="andan-descriptives-mean-absolute-deviation-around-the-median"><span class="header-section-number">24.3.2.2</span> Среднее абсолютное отклонение от медианы</h4>
<div class="lab-chapter lab-middle">

</div>
</section>
<section id="andan-descriptives-median-absolute-deviation" class="level4" data-number="24.3.2.3">
<h4 data-number="24.3.2.3" class="anchored" data-anchor-id="andan-descriptives-median-absolute-deviation"><span class="header-section-number">24.3.2.3</span> Медианное абсолютное отклонение</h4>
<div class="lab-chapter lab-middle">

</div>
</section>
</section>
<section id="andan-descriptives-variance" class="level3" data-number="24.3.3">
<h3 data-number="24.3.3" class="anchored" data-anchor-id="andan-descriptives-variance"><span class="header-section-number">24.3.3</span> Дисперсия</h3>
<div class="lab-chapter lab-junior">

</div>
<section id="andan-descriptives-population-variance" class="level4" data-number="24.3.3.1">
<h4 data-number="24.3.3.1" class="anchored" data-anchor-id="andan-descriptives-population-variance"><span class="header-section-number">24.3.3.1</span> Дисперсия генеральной совокупности</h4>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-sample-variance" class="level4" data-number="24.3.3.2">
<h4 data-number="24.3.3.2" class="anchored" data-anchor-id="andan-descriptives-sample-variance"><span class="header-section-number">24.3.3.2</span> Дисперсия выборки</h4>
<div class="lab-chapter lab-junior">

</div>
</section>
</section>
<section id="andan-descriptives-standard-deviation" class="level3" data-number="24.3.4">
<h3 data-number="24.3.4" class="anchored" data-anchor-id="andan-descriptives-standard-deviation"><span class="header-section-number">24.3.4</span> Стандартное отклонение</h3>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-quantiles" class="level3" data-number="24.3.5">
<h3 data-number="24.3.5" class="anchored" data-anchor-id="andan-descriptives-quantiles"><span class="header-section-number">24.3.5</span> Квантили</h3>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-quartiles" class="level3" data-number="24.3.6">
<h3 data-number="24.3.6" class="anchored" data-anchor-id="andan-descriptives-quartiles"><span class="header-section-number">24.3.6</span> Квартили</h3>
<div class="lab-chapter lab-junior">

</div>
</section>
</section>
<section id="andan-descriptives-skewness" class="level2" data-number="24.4">
<h2 data-number="24.4" class="anchored" data-anchor-id="andan-descriptives-skewness"><span class="header-section-number">24.4</span> Асимметрия</h2>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-kurtosis" class="level2" data-number="24.5">
<h2 data-number="24.5" class="anchored" data-anchor-id="andan-descriptives-kurtosis"><span class="header-section-number">24.5</span> Эксцесс</h2>
<div class="lab-chapter lab-junior">

</div>
</section>
<section id="andan-descriptives-final" class="level2" data-number="24.6">
<h2 data-number="24.6" class="anchored" data-anchor-id="andan-descriptives-final"><span class="header-section-number">24.6</span> Итоги</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-shepard71" class="csl-entry" role="doc-biblioentry">
Shepard, Roger N., and Jacqueline Metzler. 1971. <span>“Mental Rotation of Three-Dimensional Objects.”</span> <em>Science</em> 171 (3972): 701–3. <a href="https://doi.org/10.1126/science.171.3972.701">https://doi.org/10.1126/science.171.3972.701</a>.
</div>
<div id="ref-stevens46" class="csl-entry" role="doc-biblioentry">
Stevens, S. S. 1946. <span>“On the Theory of Scales of Measurement.”</span> <em>Science</em> 103 (2684): 677–80. <a href="https://doi.org/10.1126/science.103.2684.677">https://doi.org/10.1126/science.103.2684.677</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Mass (uncountable) noun<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Countable noun, plural in this case<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Здесь в примере локальный максимум функции плотности вероятности на интервале <span class="math inline">\((-4, \, 4)\)</span> совпадает с глобальным максимумом — мы об этом знаем, потому что форма распределения нам известна. В случае эмпрического распределения корректнее говорить именно о локальном максимуме, так как глобальный максимум нам не доступен ввиду того, что мы работаем с выборкой.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Скопировано!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Скопировано!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./part-andan.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Методы анализа данных</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./andan-ttest.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Сравнение средних</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>